# Generated by Django 5.1.4 on 2025-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts1', models.FloatField()),
                ('ts2', models.FloatField()),
                ('ts3', models.FloatField()),
                ('ts4', models.FloatField()),
                ('operation', models.CharField(max_length=20)),
                ('result', models.FloatField()),
            ],
        ),
    ]
