# Generated by Django 5.1.4 on 2025-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='operation',
            field=models.CharField(choices=[('Summation', 'Cộng'), ('Subtraction', 'Trừ'), ('Product', 'Nhân')], max_length=20),
        ),
    ]
